### ISSUE TITLE
Unable to create note

### ISSUE THREAD

**Issue by Duifkruid** [chhoumann/PodNotes#87]
Hi Christian, 

First off, thank you for all your fantastic obsidian plugins; I am an enthusiastic user of the major three (I think those are the three but I might be mistaken). 

I bumped into an issue with podnotes since this week. Each time I try to create a note by right clicking the podcast in the sidebar, an error message appears, warning me: "failed to create {{the note}}.md". I have tried altering the template (I use the modal inside the options of the plugin, I usually tinker more and might write a small script to use in quickadd, but this worked fine and did what I wanted, so just used your handlebar templates as stated in the documentation). I have also tried reinstalling the plugin. I tried altering the metadata from yaml/properties to inline. Nothing helps: it used to work like a charm, now nothing budges. 

This is the template I use: 
```markdown
---
title: {{podcast}}
episode: {{title}}
published: {{date:YYYY-MM-DD}}
link: {{url}}
---
# Thoughts on {{title}}
![]({{artwork}})

## Description
>[!description]
{{description:> }}

### Content
>[!content]
{{content:> }}
```
The console has two warnings on podnotes: 
- The first one, upon start: 
```shell
app.js:1 Error: Plugin "podnotes" is not passing Component in renderMarkdown. This is needed to avoid memory leaks when embedded contents register global event handlers.
    at t.render (app.js:1:1236200)
    at t.renderMarkdown (app.js:1:1235981)
    at updateTimestampDemo (plugin:podnotes:4423:42)
    at PodNotesSettingsTab.addNoteSettings (plugin:podnotes:4425:5)
    at PodNotesSettingsTab.display (plugin:podnotes:4369:10)
    at SettingsSearch.getTabResources (plugin:settings-search:229:15)
    at SettingsSearch.buildPluginResources (plugin:settings-search:129:12)
    at eval (plugin:settings-search:131:29)
```
- and this one, after trying to create the note: 
```shell
Error: Folder already exists.
    at t.<anonymous> (app.js:1:710467)
    at app.js:1:237002
    at Object.next (app.js:1:237107)
    at a (app.js:1:235825)
eval @ plugin:podnotes:6560
```
The folder indeed already exists, bc it is the folder stated in podnote settings as the note creation file path, which does not give errors in the example of values below it, and which, up until now, used to work fine: 
```markdown
Blog/Reference Notes/Podcasts/{{podcast}}/{{podcast}} - {{title}}
```

There probably is something I am overlooking, but maybe this has something to do with properties being introduced? I have not used the plugin since the introduction, I must admit. 

Thank you for your time, hoping I am just doing something wrong and it is easily adjusted, 

Anne

**Comment by kliiic** [comment]
Hi Anne,

I've had the exactly same issue, but I've somehow soved it. I can't tell exactly how, but one would describe it as "fiddling" with Note creation file path. I forced Podnotes to create brand new folder, and then step by step I got the path I once intended to use. I know is is not much of a debugging, but I'm convinced the problem is in the path, not the template. 

Hope it helps
Ondra

**Comment by chhoumann** [comment]
Looked into this — the actionable failure here is the second console error, **`Folder already exists`**, not the benign `renderMarkdown` warning.

**Root cause:** your note path template targets an existing folder (`Blog/Reference Notes/Podcasts/{{podcast}}/…`). PodNotes created folders with a hand-rolled loop that guarded each prefix with the case-**sensitive** `getAbstractFileByPath` and then called `Vault.createFolder`. On a case-insensitive filesystem (default on macOS/Windows), or with Unicode-normalized folder names, that lookup can miss a folder that is genuinely present, so `createFolder` throws `Folder already exists` — which bubbled up as the generic "Failed to create note". The illegal-character half (special characters in `{{podcast}}`/`{{title}}`) was already fixed by #99.

Reproduced the `createFolder`-on-existing-folder throw in a real vault, then confirmed the fix: with the folder present but the lookup forced to miss, note creation now succeeds with zero errors.

Fixed in #192, which routes folder creation through a hardened `ensureFolderExists` that tolerates "already exists" while still surfacing genuine failures. That PR `Closes #87` (and #22) — it'll close automatically on merge.
